/*
-- Query: SELECT * FROM rentalsystem.users
LIMIT 0, 1000

-- Date: 2025-08-27 21:26
*/
INSERT INTO `` (`id`,`password`,`phone`,`username`,`role_id`,`email`,`avatar_url`,`email_verified`,`enabled`,`first_name`,`last_name`,`provider`,`provider_id`,`updated_at`,`account_expired`,`account_locked`,`credentials_expired`,`last_login`,`created_at`) VALUES (1,'$2a$10$Lr5iGDqc6h5cnsVmOAav3.IXCp5.rLd5Pt4d0TQr/ZCp7vBrTMQ9i','+840972756489','testRegister1',1,'testRegister1@gmail.com',NULL,'0','0',NULL,NULL,'GITHUB',NULL,NULL,'0','0','0',NULL,'2025-08-20 20:05:28');
INSERT INTO `` (`id`,`password`,`phone`,`username`,`role_id`,`email`,`avatar_url`,`email_verified`,`enabled`,`first_name`,`last_name`,`provider`,`provider_id`,`updated_at`,`account_expired`,`account_locked`,`credentials_expired`,`last_login`,`created_at`) VALUES (2,'$2a$10$xxQUc6NUaw/GUeLqLgjsUOgWrboYMcTdNtMIJDxSCDDBm6uuZ2lrS','+840972756486','testRegister2',1,'testRegister2@gmail.com',NULL,'0','0',NULL,NULL,'GITHUB',NULL,NULL,'0','0','0',NULL,'2025-08-20 20:05:28');
INSERT INTO `` (`id`,`password`,`phone`,`username`,`role_id`,`email`,`avatar_url`,`email_verified`,`enabled`,`first_name`,`last_name`,`provider`,`provider_id`,`updated_at`,`account_expired`,`account_locked`,`credentials_expired`,`last_login`,`created_at`) VALUES (3,'$2a$10$bkKp7Rcx8q9JKR.DIkGfkukZsOZzjbrNvl/tmdNWMhabvLtFgFml2','+840972756484','testRegister3',1,'testRegister3@gmail.com',NULL,'0','0',NULL,NULL,'GITHUB',NULL,NULL,'0','0','0',NULL,'2025-08-20 20:05:28');
INSERT INTO `` (`id`,`password`,`phone`,`username`,`role_id`,`email`,`avatar_url`,`email_verified`,`enabled`,`first_name`,`last_name`,`provider`,`provider_id`,`updated_at`,`account_expired`,`account_locked`,`credentials_expired`,`last_login`,`created_at`) VALUES (4,'$2a$10$8hDmR2K1UjYhARi.jPayWu8KzxbUfTvE8Jf..2w3IqHLyWP9BYQIS','0123456789','admin',3,'admin@rental.com',NULL,'0','0',NULL,NULL,'GITHUB',NULL,NULL,'0','0','0',NULL,'2025-08-20 20:05:28');
INSERT INTO `` (`id`,`password`,`phone`,`username`,`role_id`,`email`,`avatar_url`,`email_verified`,`enabled`,`first_name`,`last_name`,`provider`,`provider_id`,`updated_at`,`account_expired`,`account_locked`,`credentials_expired`,`last_login`,`created_at`) VALUES (5,'$2a$10$kFjNvClBP7c/aY4yPy1VQ.IAoLLbhpKzGWrRDXPQYrJASJhxuIr76','09704858229','admin1',1,'admin1@gmail.com',NULL,'0','0',NULL,NULL,'GITHUB',NULL,NULL,'0','0','0',NULL,'2025-08-20 20:05:28');
INSERT INTO `` (`id`,`password`,`phone`,`username`,`role_id`,`email`,`avatar_url`,`email_verified`,`enabled`,`first_name`,`last_name`,`provider`,`provider_id`,`updated_at`,`account_expired`,`account_locked`,`credentials_expired`,`last_login`,`created_at`) VALUES (6,'$2a$10$NvFc8Y1N1.b/Z9RSBJvOQutWVRhqe96w/qNrVyQt119UljqaPXc96','0972756484','testRegister4',1,'testRegister4@gmail.com',NULL,'0','0',NULL,NULL,'GITHUB',NULL,NULL,'0','0','0',NULL,'2025-08-20 20:05:28');
INSERT INTO `` (`id`,`password`,`phone`,`username`,`role_id`,`email`,`avatar_url`,`email_verified`,`enabled`,`first_name`,`last_name`,`provider`,`provider_id`,`updated_at`,`account_expired`,`account_locked`,`credentials_expired`,`last_login`,`created_at`) VALUES (7,'$2a$10$wBpZMdm7NHSZzEHSU/lU8eMAMoQevZZWKfuSw5pIfURRdoMFDgzze','0972756486','test6',1,'test6@gmail.com',NULL,'0','0',NULL,NULL,'GITHUB',NULL,NULL,'0','0','0',NULL,'2025-08-20 20:05:28');
INSERT INTO `` (`id`,`password`,`phone`,`username`,`role_id`,`email`,`avatar_url`,`email_verified`,`enabled`,`first_name`,`last_name`,`provider`,`provider_id`,`updated_at`,`account_expired`,`account_locked`,`credentials_expired`,`last_login`,`created_at`) VALUES (8,'$2a$10$YgYx.DTxbRcUM5uoaoyjkOPmw8fDQykmnUch0tEiawmofMzu7X0L.','0972756487','test7',1,'test7@gmail.com',NULL,'0','0',NULL,NULL,'GITHUB',NULL,NULL,'0','0','0',NULL,'2025-08-20 20:05:28');
INSERT INTO `` (`id`,`password`,`phone`,`username`,`role_id`,`email`,`avatar_url`,`email_verified`,`enabled`,`first_name`,`last_name`,`provider`,`provider_id`,`updated_at`,`account_expired`,`account_locked`,`credentials_expired`,`last_login`,`created_at`) VALUES (9,'$2a$10$ef8oUGiaAXTmKDSbk.9VVegSJbcgfxU2F/R4ltFiZd31I7Y1xtFH6','0972756488','test8',1,'test8@gmail.com',NULL,'0','0',NULL,NULL,'GITHUB',NULL,NULL,'0','0','0',NULL,'2025-08-20 20:05:28');
INSERT INTO `` (`id`,`password`,`phone`,`username`,`role_id`,`email`,`avatar_url`,`email_verified`,`enabled`,`first_name`,`last_name`,`provider`,`provider_id`,`updated_at`,`account_expired`,`account_locked`,`credentials_expired`,`last_login`,`created_at`) VALUES (10,'$2a$10$DWx9FwCL3aKMBd9wB3PcT.9R5AmBYYpt7O/j0ykGj.0g/3jnWr/J6','0972756489','test9',1,'test9@gmail.com',NULL,'0','0',NULL,NULL,'GITHUB',NULL,NULL,'0','0','0',NULL,'2025-08-20 20:05:28');
INSERT INTO `` (`id`,`password`,`phone`,`username`,`role_id`,`email`,`avatar_url`,`email_verified`,`enabled`,`first_name`,`last_name`,`provider`,`provider_id`,`updated_at`,`account_expired`,`account_locked`,`credentials_expired`,`last_login`,`created_at`) VALUES (11,'$2a$10$vBEkTgf.q4J8MFqR0FEvGOWGO5acQiD84jIdeYPF.PZrCBqSn9Ir6','0972756410','test10',1,'test10@gmail.com',NULL,'0','0',NULL,NULL,'GITHUB',NULL,NULL,'0','0','0',NULL,'2025-08-20 20:05:28');
INSERT INTO `` (`id`,`password`,`phone`,`username`,`role_id`,`email`,`avatar_url`,`email_verified`,`enabled`,`first_name`,`last_name`,`provider`,`provider_id`,`updated_at`,`account_expired`,`account_locked`,`credentials_expired`,`last_login`,`created_at`) VALUES (12,'$2a$10$JFUsdeP/MvQXwUEp7d6tne6BzrpKpDso76YcL0yYNm4tB.T29psJe','0987654321','host',2,'host@rental.com',NULL,'0','0',NULL,NULL,'GITHUB',NULL,NULL,'0','0','0',NULL,'2025-08-20 20:05:28');
INSERT INTO `` (`id`,`password`,`phone`,`username`,`role_id`,`email`,`avatar_url`,`email_verified`,`enabled`,`first_name`,`last_name`,`provider`,`provider_id`,`updated_at`,`account_expired`,`account_locked`,`credentials_expired`,`last_login`,`created_at`) VALUES (13,'$2a$10$Ht7M97.oi.Dwh96MNGhd4uKdTGfbIs/WJ/MT9HV1tnDKRMlk/ZWfK','0111222333','user',2,'usertest@rental.com',NULL,'0','0',NULL,NULL,'GITHUB',NULL,NULL,'0','0','0',NULL,'2025-08-20 20:05:28');
INSERT INTO `` (`id`,`password`,`phone`,`username`,`role_id`,`email`,`avatar_url`,`email_verified`,`enabled`,`first_name`,`last_name`,`provider`,`provider_id`,`updated_at`,`account_expired`,`account_locked`,`credentials_expired`,`last_login`,`created_at`) VALUES (14,'$2a$10$MttVmGv0TFJhPhGgHZobn.8sMSZQFOfiXkfS04CKD0y6lYUMCZnlK','0555666777','john',1,'john@example.com',NULL,'0','0',NULL,NULL,'GITHUB',NULL,NULL,'0','0','0',NULL,'2025-08-20 20:05:28');
INSERT INTO `` (`id`,`password`,`phone`,`username`,`role_id`,`email`,`avatar_url`,`email_verified`,`enabled`,`first_name`,`last_name`,`provider`,`provider_id`,`updated_at`,`account_expired`,`account_locked`,`credentials_expired`,`last_login`,`created_at`) VALUES (15,'$2a$10$Hlb5gaolUtiuDoFAs/YI..8A17JoPcyN.3LYYQmEvssRber2ZRUTe','0972756425','user2',1,'user2@gmail.com',NULL,'0','0',NULL,NULL,'GITHUB',NULL,NULL,'0','0','0',NULL,'2025-08-20 20:05:28');
INSERT INTO `` (`id`,`password`,`phone`,`username`,`role_id`,`email`,`avatar_url`,`email_verified`,`enabled`,`first_name`,`last_name`,`provider`,`provider_id`,`updated_at`,`account_expired`,`account_locked`,`credentials_expired`,`last_login`,`created_at`) VALUES (16,'$2a$10$VS05e2YT.jdkKtAC.uUy/uDJfTnnDwqvacbEQmAI4OpOQsc4b9nYm','0972756403','user3',2,'user3update@gmail.com',NULL,'0','0',NULL,NULL,'GITHUB',NULL,NULL,'0','0','0',NULL,'2025-08-20 20:05:28');
INSERT INTO `` (`id`,`password`,`phone`,`username`,`role_id`,`email`,`avatar_url`,`email_verified`,`enabled`,`first_name`,`last_name`,`provider`,`provider_id`,`updated_at`,`account_expired`,`account_locked`,`credentials_expired`,`last_login`,`created_at`) VALUES (17,'$2a$10$oDv8RtOH8oqKKmQdxoHxY.2L0ulCKSfrdLOrz1AjwQg4b0oqByLwe','0972756444','user4',1,'user4@gmail.com',NULL,'0','0',NULL,NULL,'GITHUB',NULL,NULL,'0','0','0',NULL,'2025-08-20 20:05:28');
